import { StoryVersion } from '@aniplay/contracts';

/**
 * "The Salt Road" — a travel-and-survival world.
 *
 * A third distinct spine: a real map with travel costs, a hard world clock, and
 * LETHAL defeat. Exists partly to prove the engine enforces a permanent-death
 * ruleset that the other launch worlds deliberately do not use.
 */

const raw = {
  id: 'sv_salt_road_1',
  storyId: 'story_salt_road',
  version: 1,
  title: 'The Salt Road',
  fantasyLabel: 'Eleven days of road. Nine days of water.',
  hook: 'You are carrying something across the flats that three other people want, and the water will not stretch.',
  premise:
    'The salt flats between Ossun and the coast take eleven days on foot and there is water at four places, none of them reliable. ' +
    'You are carrying a sealed case for a woman who paid in advance and did not say what is in it, alongside a guide who has done this route nine times, a pilgrim who should not be out here, and a man who joined at the second well and has never once been asleep when you woke up. ' +
    'The flats do not have monsters. They have distance, arithmetic, and the fact that four people drink faster than one. ' +
    'Every day you choose a pace and a route, and every choice spends water you cannot get back. Out here dying is permanent, and the road does not care whose fault it was.',
  creatorId: 'creator_official',
  creatorName: 'ANIMA Studio',
  official: true,
  coverImage: null,
  keyArt: null,
  tags: ['Survival', 'Adventure', 'Mystery', 'Dark fantasy'],
  mechanicsChips: ['Travel', 'Resource management', 'Trust', 'Hard choices'],
  contentDescriptors: ['FANTASY_VIOLENCE', 'PERMANENT_DEATH', 'MORAL_AMBIGUITY', 'PSYCHOLOGICAL_THEMES'],
  intensity: 'INTENSE',
  creatorNote:
    'Death is permanent here, and that is the point. The flats are not cruel; they are indifferent, and indifference is harder to argue with.',
  rules: {
    defeatMode: 'LETHAL',
    progressionMode: 'MILESTONE',
    revealExactDc: true,
    revealCheckMath: true,
    allowsCombat: true,
    allowsRomance: false,
    startingLocationId: 'ossun_gate',
    startWorldMinute: 5 * 60,
    hardCanon: [
      'There are four water sources between Ossun and the coast, and the third is unreliable.',
      'Nothing lives on the flats. What you see out there is weather or a person.',
      'The case is sealed with a maker’s mark from a house that closed forty years ago.',
      'Salt preserves. Nothing on the flats decays, including what was left there.',
    ],
    toneGuide:
      'Flat white light and arithmetic. Threat is logistical, not monstrous. People are decent right up until the water runs low, and then they are still mostly decent, which is worse.',
    forkCostCredits: 120,
  },
  attributes: { might: 12, agility: 11, mind: 12, presence: 11, resolve: 13, arcana: 8 },
  skills: [
    { id: 'endurance', name: 'Endurance', attribute: 'might', description: 'Walking when you would rather not.' },
    { id: 'navigation', name: 'Navigation', attribute: 'mind', description: 'Knowing where the well is from where the light is.' },
    { id: 'survival', name: 'Survival', attribute: 'mind', description: 'Water, shade, and what the sky is about to do.' },
    { id: 'perception', name: 'Perception', attribute: 'mind', description: 'Seeing the thing on the horizon before it sees you.' },
    { id: 'persuasion', name: 'Persuasion', attribute: 'presence', description: 'Holding a group together on short water.' },
    { id: 'blades', name: 'Blades', attribute: 'might', description: 'The last argument anyone wants to have out here.' },
    { id: 'composure', name: 'Composure', attribute: 'resolve', description: 'Doing the arithmetic anyway.' },
  ],
  resources: [
    {
      id: 'health',
      name: 'Health',
      max: 20,
      start: 20,
      regenPerHour: 0,
      polarity: 'GOOD_HIGH',
      displayPriority: 1,
      visible: true,
      zeroStateConsequence: 'You go down on the flats. In this world that is the end of the run.',
      color: '#FF5B69',
    },
    {
      id: 'water',
      name: 'Water',
      max: 60,
      start: 42,
      regenPerHour: -1,
      polarity: 'GOOD_HIGH',
      displayPriority: 2,
      visible: true,
      zeroStateConsequence: 'Everything is a Resolve check, and then it stops being a check.',
      color: '#43D6A4',
    },
    {
      id: 'strain',
      name: 'Strain',
      max: 100,
      start: 0,
      regenPerHour: -2,
      polarity: 'GOOD_LOW',
      displayPriority: 3,
      visible: true,
      zeroStateConsequence: 'Rested. It will not last.',
      color: '#F6BE55',
    },
  ],
  items: [
    {
      id: 'sealed_case',
      name: 'The Sealed Case',
      tags: ['quest'],
      questItem: true,
      droppable: false,
      description: 'Brass corners, a maker’s mark, and heavier than it has any right to be.',
      loreText: 'The mark belongs to a house that closed forty years ago. The solder is newer than that.',
      icon: 'case',
    },
    {
      id: 'canteen',
      name: 'Full Canteen',
      tags: ['consumable'],
      stackable: true,
      maxStack: 4,
      consumable: { resourceId: 'water', amount: 15, consumesItem: true },
      description: 'Two days if you are careful. One if you are not.',
      loreText: 'The dent is from someone else’s journey.',
      icon: 'canteen',
    },
    {
      id: 'salt_veil',
      name: 'Salt Veil',
      tags: ['gear'],
      equipSlot: 'head',
      skillModifiers: { endurance: 2, perception: -1 },
      description: 'Keeps the glare and the crust off. Narrows what you can see.',
      loreText: 'Every guide wears one. Every guide complains about it.',
      icon: 'veil',
    },
    {
      id: 'guide_map',
      name: "Ferrow's Map",
      tags: ['tool'],
      equipSlot: 'hand',
      skillModifiers: { navigation: 3 },
      rarity: 'Rare',
      description: 'Nine crossings marked in nine different inks. The third well has a question mark.',
      loreText: 'One route is scratched out entirely. No note as to why.',
      icon: 'map',
    },
  ],
  abilities: [
    {
      id: 'read_the_flat',
      name: 'Read the Flat',
      tags: ['survival'],
      description: 'Take the light, the crust, and the horizon, and work out what the next six hours cost.',
      affordances: ['read the flat', 'study the horizon', 'check the ground', 'work out the route'],
      costs: [{ resourceId: 'water', amount: 1 }],
      cooldownMinutes: 240,
      targetRule: 'NONE',
      check: { attribute: 'mind', skillId: 'navigation', baseDc: 13 },
      unlockedByDefault: true,
    },
    {
      id: 'ration',
      name: 'Ration',
      tags: ['survival'],
      description: 'Cut everyone down to the minimum, including yourself, and hold the group to it.',
      affordances: ['ration the water', 'cut the rations', 'put everyone on short water'],
      costs: [],
      cooldownMinutes: 720,
      targetRule: 'MULTI',
      check: { attribute: 'presence', skillId: 'persuasion', baseDc: 14 },
      unlockedByDefault: true,
    },
  ],
  locations: [
    {
      id: 'ossun_gate',
      name: 'Ossun Gate',
      shortName: 'Ossun',
      description:
        'The last wall before the flats. Water sellers, a notice board of names that did not arrive, and a road that goes white about a mile out.',
      artDirection: 'Dawn, low mud-brick wall, a bleached road running to a white horizon, water barrels stacked in shade.',
      stageImage: null,
      discoveredByDefault: true,
      mapPosition: { x: 0.12, y: 0.8 },
      ambientSfx: ['wind_low', 'market'],
      connections: [{ to: 'first_well', travelMinutes: 720, label: 'Out onto the flats' }],
    },
    {
      id: 'first_well',
      name: 'The First Well',
      shortName: 'First well',
      description:
        'A stone ring and a windlass that works. Everyone stops here, so everyone meets here, and the ground is scuffed with everyone.',
      artDirection: 'Midday white glare, low stone well ring, three long shadows, nothing else to the horizon.',
      stageImage: null,
      discoveredByDefault: false,
      mapPosition: { x: 0.35, y: 0.62 },
      ambientSfx: ['wind_low', 'rope'],
      connections: [
        { to: 'ossun_gate', travelMinutes: 720, label: 'Back toward Ossun' },
        { to: 'the_wrecks', travelMinutes: 840, label: 'North, past the wrecks' },
        { to: 'second_well', travelMinutes: 660, label: 'Straight on' },
      ],
    },
    {
      id: 'the_wrecks',
      name: 'The Wrecks',
      shortName: 'Wrecks',
      description:
        'Four wagons in a rough line, upright, still loaded. Salt preserves. Nobody has taken anything, and nobody says why.',
      artDirection: 'Evening light, four intact wagons half-buried in white crust, long blue shadows.',
      stageImage: null,
      discoveredByDefault: false,
      mapPosition: { x: 0.55, y: 0.32 },
      ambientSfx: ['wind_high', 'creak'],
      connections: [
        { to: 'first_well', travelMinutes: 840, label: 'Back south' },
        { to: 'third_well', travelMinutes: 600, label: 'On toward the third well' },
      ],
    },
    {
      id: 'second_well',
      name: 'The Second Well',
      shortName: 'Second well',
      description: 'Sound, deep, and crowded. The last certain water before the arithmetic gets serious.',
      artDirection: 'Afternoon, a walled well with a canvas awning, three or four other travellers keeping distance.',
      stageImage: null,
      discoveredByDefault: false,
      mapPosition: { x: 0.55, y: 0.62 },
      ambientSfx: ['wind_low', 'voices'],
      connections: [
        { to: 'first_well', travelMinutes: 660, label: 'Back to the first well' },
        { to: 'third_well', travelMinutes: 780, label: 'On to the third' },
      ],
    },
    {
      id: 'third_well',
      name: 'The Third Well',
      shortName: 'Third well',
      description:
        'Marked with a question mark on every map worth having. Sometimes it holds. The approach is scattered with things people decided to stop carrying.',
      artDirection: 'Harsh noon, a dry-looking stone mouth, discarded packs and boots scattered on white ground.',
      stageImage: null,
      discoveredByDefault: false,
      mapPosition: { x: 0.78, y: 0.45 },
      ambientSfx: ['wind_high'],
      connections: [
        { to: 'second_well', travelMinutes: 780, label: 'Back to the second well' },
        { to: 'the_wrecks', travelMinutes: 600, label: 'Back to the wrecks' },
      ],
    },
  ],
  characters: [
    {
      id: 'ferrow',
      name: 'Ferrow',
      role: 'Guide, nine crossings',
      pronouns: 'she/her',
      publicTraits: ['Flat-voiced', 'Exact', 'Does not reassure'],
      hiddenDrives: [
        'Her eighth crossing lost two people at the third well and she has not been back since.',
        'She took this job because the case is going to the coast and she needs to see who collects it.',
      ],
      values: ['Arithmetic', 'Telling people the truth about water'],
      fears: ['The third well', 'Being trusted more than she deserves'],
      socialStyle: 'States the cost and lets you decide. Never argues twice.',
      boundaries: ['Will not lie about the water', 'Will not carry anyone she cannot carry'],
      goals: ['Reach the coast', 'See who takes delivery'],
      secrets: [
        {
          id: 'ferrow_eighth',
          fact: 'Ferrow lost two travellers at the third well on her eighth crossing.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 40+, or arriving at the third well with her.',
        },
      ],
      speechStyle: 'Short sentences. Numbers wherever a number will do. No comfort offered or expected.',
      topics: ['the water', 'the third well', 'the route', 'who hired you'],
      voiceSamples: [
        'Nine days of water. Eleven days of road. You do the rest.',
        'I am not going to tell you it will be fine. I am going to tell you when to drink.',
        'The third well is a question mark on every map worth having. Mine included.',
      ],
      appearance: 'Weathered, salt veil pushed back, forearms wrapped, a map case she never puts down.',
      visualHook:
        'Nine short parallel pale scar-lines cut into the inside of her left forearm, one per crossing, the ninth visibly shorter than the rest.',
      silhouette:
        'Weathered and economical, salt veil pushed back off the face, forearms wrapped, a map case strapped across the chest.',
      artSeed: 'ferrow-v1',
      portrait: null,
      expressions: ['neutral', 'flat', 'alert', 'grim', 'relieved'],
      voiceId: 'voice_ferrow',
      homeLocationId: 'first_well',
      knowledgeScope: [],
      schedule: [],
      startingRelationship: { trust: 15, affection: 0, respect: 15, fear: 0, rivalry: 0 },
      attributes: { might: 13, agility: 12, mind: 15, presence: 11, resolve: 15, arcana: 8 },
      gates: [
        {
          id: 'ferrow_tells_you',
          kind: 'TRUST',
          label: 'Ferrow will tell you about the eighth crossing',
          requires: { trust: 40, respect: 30 },
        },
      ],
      combatant: { health: 20, defenseDc: 14, damage: 5, tags: ['veteran'] },
    },
    {
      id: 'oren',
      name: 'Oren',
      role: 'Joined at the second well',
      pronouns: 'he/him',
      publicTraits: ['Easy company', 'Helpful', 'Never asleep first'],
      hiddenDrives: [
        'He was sent to make sure the case reaches the coast, and to make sure of nothing else.',
        'He genuinely likes the group, which complicates his instructions.',
      ],
      values: ['Finishing what he agreed to'],
      fears: ['Having to choose'],
      socialStyle: 'Warm, useful, and always slightly better informed than he should be.',
      boundaries: ['Will not start anything', 'Will not abandon the group first'],
      goals: ['See the case delivered'],
      secrets: [
        {
          id: 'oren_sent',
          fact: 'Oren was sent by the case’s recipient and joined the group on purpose.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Perception at the wrecks, or trust 45+ on short water.',
        },
      ],
      speechStyle: 'Friendly, deflecting, asks two questions for every one he answers.',
      topics: ['where he came from', 'the case', 'the wrecks', 'what he does for work'],
      voiceSamples: [
        'I will take the first watch. You look like the arithmetic is keeping you up.',
        'I came up from the coast side. Long story, and not an interesting one.',
        'Ask me again when we have water. I will probably tell you.',
      ],
      appearance: 'Thirties, sunburnt over an older tan, a good pack he did not buy in Ossun.',
      visualHook:
        "A coat and pack in far better condition than anyone else's on this road, and the only uncracked, unweathered hands in the group.",
      silhouette:
        'Easy and open, sunburnt over an older tan, a good pack carried too comfortably.',
      artSeed: 'oren-v1',
      portrait: null,
      expressions: ['friendly', 'neutral', 'watchful', 'caught', 'resolved'],
      voiceId: 'voice_oren',
      homeLocationId: 'second_well',
      knowledgeScope: [],
      schedule: [],
      startingRelationship: { trust: 5, affection: 10, respect: 5, fear: 0, rivalry: 0 },
      attributes: { might: 13, agility: 13, mind: 12, presence: 13, resolve: 13, arcana: 8 },
      gates: [
        {
          id: 'oren_admits',
          kind: 'TRUST',
          label: 'Oren will tell you who sent him',
          requires: { trust: 45, flagsSet: ['suspect_oren'] },
        },
      ],
      combatant: { health: 22, defenseDc: 15, damage: 6, tags: ['professional'] },
    },
    {
      id: 'sabe',
      name: 'Sabe',
      role: 'Pilgrim',
      pronouns: 'they/them',
      publicTraits: ['Cheerful', 'Badly equipped', 'Absolutely certain'],
      hiddenDrives: [
        'They are walking to the coast to scatter someone, and have not told anyone.',
        'They will not turn back, and know exactly what that might cost.',
      ],
      values: ['Keeping a promise to the dead'],
      fears: ['Being sent home', 'Being a burden and knowing it'],
      socialStyle: 'Talks constantly, thanks everyone, apologises for nothing important.',
      boundaries: ['Will not turn back', 'Will not take more than their share'],
      goals: ['Reach the coast'],
      secrets: [
        {
          id: 'sabe_ashes',
          fact: 'Sabe is carrying ashes and has told nobody.',
          visibility: 'NPC_PRIVATE',
          revealHint: 'Trust 35+, or an Insight read at a low point.',
        },
      ],
      speechStyle: 'Bright, run-on, self-deprecating. Goes very quiet when it matters.',
      topics: ['why they are out here', 'the coast', 'their pack', 'what they packed wrong'],
      voiceSamples: [
        'I know. I packed like an idiot. You may say it once and then we move on.',
        'I am not turning round. You can be annoyed about that, it is allowed.',
        'Is it much further? Do not answer that. Actually, answer it.',
      ],
      appearance: 'Young, sun-blistered, a pack a third too heavy, boots that were not made for this.',
      visualHook:
        'A small sealed clay urn lashed to the very top of an overloaded pack, in plain sight, that nobody has asked about yet.',
      silhouette:
        'Young and overburdened, listing slightly under a pack a third too heavy, boots made for a city.',
      artSeed: 'sabe-v1',
      portrait: null,
      expressions: ['bright', 'neutral', 'flagging', 'quiet', 'determined'],
      voiceId: 'voice_sabe',
      homeLocationId: 'ossun_gate',
      knowledgeScope: [],
      schedule: [],
      startingRelationship: { trust: 20, affection: 20, respect: 0, fear: 0, rivalry: 0 },
      attributes: { might: 9, agility: 11, mind: 11, presence: 13, resolve: 15, arcana: 8 },
      gates: [
        {
          id: 'sabe_tells_you',
          kind: 'TRUST',
          label: 'Sabe will tell you what they are carrying',
          requires: { trust: 35, affection: 30 },
        },
      ],
      combatant: { health: 12, defenseDc: 11, damage: 2, tags: ['untrained'] },
    },
  ],
  factions: [],
  quests: [
    {
      id: 'q_delivery',
      title: 'The Delivery',
      summary: 'Get the case to the coast. Eleven days of road, nine days of water.',
      kind: 'MAIN',
      startsActive: true,
      involvedCharacterIds: ['ferrow', 'oren', 'sabe'],
      involvedLocationIds: ['ossun_gate', 'first_well', 'second_well', 'third_well'],
      knownRewardCopy: 'Payment on delivery, and the name of whoever collects.',
      steps: [
        {
          id: 'step_first_well',
          playerCopy: 'Reach the first well.',
          directorNotes: 'Twelve hours of walking. Establish the arithmetic before any drama.',
          succeedWhen: { atLocation: 'first_well' },
          rewards: { xp: 50, items: [], flags: [] },
        },
        {
          id: 'step_second_well',
          playerCopy: 'Reach the second well with water to spare.',
          directorNotes: 'The last certain water. Whatever the group decides here, they live with after.',
          enterWhen: { atLocation: 'first_well' },
          succeedWhen: { atLocation: 'second_well' },
          rewards: { xp: 70, items: [{ itemId: 'canteen', qty: 1 }], flags: [] },
        },
        {
          id: 'step_third_well',
          playerCopy: 'Find out whether the third well holds.',
          directorNotes: 'The promise pays off here. Ferrow will not want to go, and will go.',
          enterWhen: { atLocation: 'second_well' },
          succeedWhen: { atLocation: 'third_well' },
          rewards: { xp: 120, items: [], flags: ['reached_third_well'] },
        },
      ],
    },
    {
      id: 'q_the_wrecks',
      title: 'Four Wagons',
      summary: 'Four wagons, upright, still loaded. Nobody has taken anything.',
      kind: 'SIDE',
      startsActive: false,
      involvedCharacterIds: ['ferrow', 'oren'],
      involvedLocationIds: ['the_wrecks'],
      knownRewardCopy: 'Whatever is still on them, and why it is still on them.',
      discoverWhen: { flagsSet: ['heard_about_wrecks'] },
      steps: [
        {
          id: 'step_reach_wrecks',
          playerCopy: 'Go north and see the wrecks for yourself.',
          directorNotes: 'Costs fourteen hours and a lot of water. That cost is the whole decision.',
          succeedWhen: { atLocation: 'the_wrecks' },
          rewards: { xp: 80, items: [{ itemId: 'guide_map', qty: 1 }], flags: ['suspect_oren'] },
        },
      ],
    },
  ],
  promises: [
    {
      id: 'promise_third_well',
      kind: 'BOSS',
      label: 'The third well, and whether it holds',
      seedHint: 'A question mark on every map worth having.',
      payoffHint: 'Ferrow lost two people here and has not been back.',
      weight: 1,
    },
    {
      id: 'promise_case',
      kind: 'MYSTERY',
      label: 'What is in the case, and who is coming for it',
      seedHint: 'A maker’s mark from a house that closed forty years ago.',
      payoffHint: 'Oren joined the group on purpose.',
      weight: 0.9,
    },
    {
      id: 'promise_sabe',
      kind: 'RELATIONSHIP',
      label: 'Sabe, who should not be out here and will not turn back',
      seedHint: 'A pack a third too heavy and boots that were not made for this.',
      payoffHint: 'They are carrying ashes to the coast.',
      weight: 0.8,
    },
  ],
  archetypes: [
    {
      id: 'arch_courier',
      name: 'Courier',
      blurb: 'You have carried worse for stranger people. Usually not this far.',
      attributeBonus: { might: 1, resolve: 2 },
      skillProficiencies: { endurance: 3, composure: 2 },
      startingItems: [
        { itemId: 'sealed_case', qty: 1 },
        { itemId: 'canteen', qty: 2 },
        { itemId: 'salt_veil', qty: 1 },
      ],
      startingAbilities: [],
    },
    {
      id: 'arch_surveyor',
      name: 'Surveyor',
      blurb: 'You read ground for a living. The flats are just very boring ground.',
      attributeBonus: { mind: 3 },
      skillProficiencies: { navigation: 3, survival: 2, perception: 2 },
      startingItems: [
        { itemId: 'sealed_case', qty: 1 },
        { itemId: 'canteen', qty: 1 },
      ],
      startingAbilities: [],
    },
    {
      id: 'arch_outrider',
      name: 'Outrider',
      blurb: 'You were paid to protect a caravan once. It went badly and you learned a lot.',
      attributeBonus: { might: 2, agility: 1 },
      skillProficiencies: { blades: 3, perception: 2, endurance: 1 },
      startingItems: [
        { itemId: 'sealed_case', qty: 1 },
        { itemId: 'canteen', qty: 1 },
        { itemId: 'salt_veil', qty: 1 },
      ],
      startingAbilities: [],
    },
  ],
  setupFields: [
    { id: 'displayName', label: 'What name is on the contract?', kind: 'TEXT', required: true, maxLength: 40, placeholder: 'e.g. Dax Oro' },
    { id: 'pronouns', label: 'Pronouns', kind: 'TEXT', required: false, maxLength: 24, placeholder: 'e.g. they/them' },
    { id: 'archetype', label: 'What did you do before this?', kind: 'ARCHETYPE', required: false },
    {
      id: 'worldKnowsAboutYou',
      label: 'Why did she pick you?',
      kind: 'TEXT',
      required: false,
      maxLength: 300,
      placeholder: 'e.g. I am the only courier who came back from the last crossing.',
    },
  ],
  opening:
    'The road goes white about a mile out, and stays white for eleven days.\n\n' +
    'Ferrow checks your canteens without asking, one by one, and does the arithmetic out loud so nobody can pretend later that they did not hear it.\n\n' +
    '"Nine days of water. Eleven days of road." She hands the last canteen back. "There are four wells. The third one is a question mark. Anyone who wants to go home should do it from here, because from the first well it is the same distance either way."\n\n' +
    'Behind you, the pilgrim shoulders a pack a third too heavy and grins at nobody.',
  openingSuggestions: [
    'Ask Ferrow what happens if the third well is dry.',
    'Check the pilgrim’s pack before we leave.',
    'Shoulder the case and start walking.',
  ],
  publishedAt: '2026-08-27T09:00:00.000Z',
};

export const SALT_ROAD = StoryVersion.parse(raw);
