/**
 * Every world that has French text.
 *
 * Registering is a side effect of importing, so this barrel is what makes the
 * overlays exist at runtime. Generated by `npm run fr:adapt`; edit that rather
 * than this.
 */
import './hush-house.fr.js';
import './nine-weeks.fr.js';
import './understudy.fr.js';
