/**
 * Every world that has French text.
 *
 * Registering is a side effect of importing, so this barrel is what makes the
 * overlays exist at runtime. Regenerated by `npm run fr:adapt`.
 */
import './good-morning-husband.fr.js';
import './hush-house.fr.js';
import './nine-weeks.fr.js';
import './red-floor.fr.js';
import './understudy.fr.js';
