import { describe, expect, it } from 'vitest';

import { describeConformance, runFormattingConformance } from './conformance.js';
import {
  formatCompact,
  formatCurrency,
  formatDate,
  formatList,
  formatNumber,
  formatOrdinal,
  formatPercent,
  formatTimeOfDay,
  frDate,
  pluralCategory,
} from './format.js';
import { DEFAULT_LOCALE, matchLocale, resolveLocale } from './locale.js';
import { foldNarrowSpaces, NBSP, NNBSP } from './typography.js';

/**
 * These are the snapshot tests the Phase 2 step-1 gate asks for, written as
 * explicit codepoint assertions rather than `toMatchSnapshot()`.
 *
 * The difference matters. A recorded snapshot can be regenerated by anyone who
 * sees it fail, which is exactly what would happen the first time an engine
 * produced U+00A0 where CLDR says U+202F — the divergence this whole package
 * exists to eliminate would be committed as the new expectation. Spelling the
 * codepoints out makes that a deliberate act.
 */

/** Render a string with its non-ASCII codepoints named, so a failure is readable. */
function codepoints(text: string): string {
  return [...text]
    .map((c) => {
      const cp = c.codePointAt(0) ?? 0;
      return cp > 126 ? `U+${cp.toString(16).toUpperCase().padStart(4, '0')}` : c;
    })
    .join('');
}

describe('the polyfill is actually installed', () => {
  /**
   * Everything below is only true on iOS and Android because the formatjs
   * implementation is running rather than the engine's. If this test fails the
   * rest of the file is asserting this machine's ICU and proves nothing about
   * a device.
   */
  it('replaces the engine Intl with the formatjs implementation', () => {
    const polyfilled = (ctor: unknown) => (ctor as { polyfilled?: boolean }).polyfilled === true;
    expect(polyfilled(Intl.NumberFormat)).toBe(true);
    expect(polyfilled(Intl.DateTimeFormat)).toBe(true);
    expect(polyfilled(Intl.PluralRules)).toBe(true);
    expect(polyfilled(Intl.ListFormat)).toBe(true);
  });

  it('implements formatToParts, which Hermes on iOS does not', () => {
    const parts = new Intl.NumberFormat('fr-FR').formatToParts(1234);
    expect(parts.map((p) => p.type)).toEqual(['integer', 'group', 'integer']);
  });

  it('implements compact notation, which Hermes does not', () => {
    expect(() => new Intl.NumberFormat('fr-FR', { notation: 'compact' }).format(12_000)).not.toThrow();
  });
});

describe('numbers', () => {
  it('groups French thousands with a non-breaking space, folded for the body font', () => {
    expect(codepoints(formatNumber(1_234_567, 'fr'))).toBe(`1U+00A0234U+00A0567`);
  });

  it('keeps CLDR U+202F when asked for exact spacing', () => {
    expect(codepoints(formatNumber(1_234_567, 'fr', { exactSpaces: true }))).toBe(
      `1U+202F234U+202F567`,
    );
  });

  it('leaves English grouping exactly as it was', () => {
    expect(formatNumber(1_234_567, 'en')).toBe('1,234,567');
    expect(formatNumber(0, 'en')).toBe('0');
    expect(formatNumber(1234.5, 'en')).toBe('1,234.5');
  });

  it('uses a decimal comma in French', () => {
    expect(codepoints(formatNumber(1234.5, 'fr'))).toBe('1U+00A0234,5');
  });

  it('formats percentages with U+00A0 in French and none in English', () => {
    expect(codepoints(formatPercent(0.5, 'fr'))).toBe('50U+00A0%');
    expect(formatPercent(0.5, 'en')).toBe('50%');
  });

  it('puts the euro after the amount, with U+00A0', () => {
    expect(codepoints(formatCurrency(1234.5, 'EUR', 'fr'))).toBe('1U+00A0234,50U+00A0U+20AC');
    expect(formatCurrency(1234.5, 'USD', 'en')).toBe('$1,234.50');
  });

  it('compacts to lowercase k with a space in French', () => {
    expect(codepoints(formatCompact(12_000, 'fr'))).toBe('12U+00A0k');
    expect(formatCompact(12_000, 'en')).toBe('12K');
  });
});

describe('the plural categories, and the zero trap', () => {
  /**
   * The single most portable mistake in a French catalogue: copying the
   * English `one`/`other` pairs and getting zero wrong in every counted string
   * in the app.
   */
  it('treats zero as singular in French and plural in English', () => {
    expect(pluralCategory(0, 'fr')).toBe('one');
    expect(pluralCategory(0, 'en')).toBe('other');
  });

  it('agrees on one and two', () => {
    expect(pluralCategory(1, 'fr')).toBe('one');
    expect(pluralCategory(1, 'en')).toBe('one');
    expect(pluralCategory(2, 'fr')).toBe('other');
    expect(pluralCategory(2, 'en')).toBe('other');
  });

  it('gives French a many category English does not have', () => {
    expect(pluralCategory(1_000_000, 'fr')).toBe('many');
    expect(pluralCategory(1_000_000, 'en')).toBe('other');
  });
});

describe('ordinals', () => {
  it('writes the French masculine and feminine first correctly', () => {
    expect(formatOrdinal(1, 'fr')).toBe('1er');
    expect(formatOrdinal(1, 'fr', 'feminine')).toBe('1re');
  });

  it('never writes 1ère or 2ème', () => {
    for (const n of [1, 2, 3, 21]) {
      for (const gender of ['masculine', 'feminine'] as const) {
        expect(formatOrdinal(n, 'fr', gender)).not.toMatch(/è?me$|ère$/);
      }
    }
  });

  it('writes every other French ordinal with a bare e', () => {
    expect(formatOrdinal(2, 'fr')).toBe('2e');
    expect(formatOrdinal(2, 'fr', 'feminine')).toBe('2e');
    expect(formatOrdinal(21, 'fr')).toBe('21e');
  });

  it('leaves English ordinals alone', () => {
    expect(formatOrdinal(1, 'en')).toBe('1st');
    expect(formatOrdinal(2, 'en')).toBe('2nd');
    expect(formatOrdinal(3, 'en')).toBe('3rd');
    expect(formatOrdinal(4, 'en')).toBe('4th');
    expect(formatOrdinal(11, 'en')).toBe('11th');
    expect(formatOrdinal(21, 'en')).toBe('21st');
  });
});

describe('dates', () => {
  const firstOfJanuary = new Date(Date.UTC(2026, 0, 1, 12, 0, 0));
  const ninthOfSeptember = new Date(Date.UTC(2025, 8, 9, 18, 5, 0));

  it('applies the 1er rule that no formatter applies for you', () => {
    // The bug this patches: ICU and Apple both return `1 janvier 2026` here.
    expect(new Intl.DateTimeFormat('fr-FR', { dateStyle: 'long' }).format(firstOfJanuary)).toBe(
      '1 janvier 2026',
    );
    expect(frDate(firstOfJanuary)).toBe('1er janvier 2026');
  });

  it('leaves every other day of the month alone', () => {
    expect(frDate(ninthOfSeptember)).toBe('9 septembre 2025');
  });

  it('does not turn a numeric short date into an ordinal', () => {
    expect(formatDate(firstOfJanuary, 'fr', 'short')).toBe('01/01/2026');
  });

  it('lowercases French months and drops the comma before the year', () => {
    const long = formatDate(ninthOfSeptember, 'fr', 'long');
    expect(long).toBe('9 septembre 2025');
    expect(long).not.toContain(',');
  });

  it('leaves English dates exactly as they were', () => {
    expect(formatDate(firstOfJanuary, 'en', 'long')).toBe('January 1, 2026');
    expect(formatDate(ninthOfSeptember, 'en', 'short')).toBe('9/9/25');
  });

  it('formats the clock 24-hour in French and 12-hour in English', () => {
    // Asserted in UTC so the result does not depend on the machine's zone.
    const utcNoon = new Date(Date.UTC(2025, 8, 9, 16, 15, 0));
    const fr = new Intl.DateTimeFormat('fr-FR', {
      hour: '2-digit',
      minute: '2-digit',
      hourCycle: 'h23',
      timeZone: 'UTC',
    }).format(utcNoon);
    expect(fr).toBe('16:15');
    // And the exported helper agrees for the ambient zone.
    expect(formatTimeOfDay(utcNoon, 'fr')).toMatch(/^\d{2}:\d{2}$/);
    expect(formatTimeOfDay(utcNoon, 'en')).toMatch(/^\d{1,2}:\d{2}\s?(AM|PM)$/i);
  });
});

describe('lists', () => {
  it('uses no Oxford comma in French', () => {
    expect(formatList(['un', 'deux', 'trois'], 'fr')).toBe('un, deux et trois');
  });

  it('keeps the English serial comma', () => {
    expect(formatList(['one', 'two', 'three'], 'en')).toBe('one, two, and three');
  });
});

describe('typography helpers', () => {
  it('folds U+202F to U+00A0 and never to a plain space', () => {
    expect(codepoints(foldNarrowSpaces(`3${NNBSP}h`))).toBe('3U+00A0h');
    expect(foldNarrowSpaces(`3${NNBSP}h`)).not.toContain(' ');
    expect(foldNarrowSpaces(`3${NNBSP}h`)).toContain(NBSP);
  });
});

describe('locale resolution', () => {
  it('reads an Accept-Language header', () => {
    expect(resolveLocale('fr-FR,fr;q=0.9,en-US;q=0.8')).toBe('fr');
    expect(resolveLocale('en-GB,en;q=0.9')).toBe('en');
  });

  it('takes the first candidate that names a supported locale', () => {
    expect(resolveLocale(null, undefined, 'de-DE', 'fr-FR')).toBe('fr');
    expect(resolveLocale(undefined)).toBe(DEFAULT_LOCALE);
  });

  it('resolves regional French to metropolitan French rather than to English', () => {
    expect(matchLocale('fr-CA')).toBe('fr');
    expect(matchLocale('fr_BE')).toBe('fr');
  });

  it('does not match a language we have no bible for', () => {
    expect(matchLocale('de')).toBeNull();
    expect(matchLocale('')).toBeNull();
    expect(matchLocale('français')).toBeNull();
  });
});

describe('the conformance suite, which is the same list a device runs', () => {
  it('passes every expectation', () => {
    const results = runFormattingConformance();
    expect(results.length).toBeGreaterThan(25);
    expect(describeConformance(results)).toBe(`${results.length}/${results.length} formatting expectations met`);
  });
});
